/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package audiokey21;

import java.awt.Desktop;
import java.io.File;
import java.io.IOException;
//import static java.lang.System.console;
import javax.sound.sampled.AudioInputStream;
import javax.sound.sampled.AudioSystem;
import javax.sound.sampled.Clip;
import javax.sound.sampled.LineUnavailableException;
import javax.sound.sampled.UnsupportedAudioFileException;
import javax.swing.JOptionPane;

/**
 *
 * @author Guglielmo
 */
public class FinestraPrincipale extends javax.swing.JFrame {

    public MiaClipAudio MC01;
    public MiaClipAudio MC02;

    /**
     * Creates new form FinestraPrincipale
     */
    public FinestraPrincipale() {
        initComponents();

        try {

            Desktop D;
            D = Desktop.getDesktop();

            File F;
            F = new File("media/video/Introduzione.mp4");    // "fix imports" per caricare la libreria File

            D.open(F);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Errore: " + e.toString());
        }

        try {
            Thread.sleep(20000); //da fixare millisecondi 20000
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Errore: " + e.toString());
        }

       MC01 = new MiaClipAudio("Media/Audio/background.wav");
        MC01.start();
        MC01.loop(Clip.LOOP_CONTINUOUSLY);
        MC01.gain(0.0f); 
        // 0.0f   silente  0.5f  metà  1.0f pieno volume
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        jScrollPane1.setMaximumSize(new java.awt.Dimension(1920, 1080));
        jScrollPane1.getHorizontalScrollBar().setUnitIncrement(30);
        jScrollPane1.setPreferredSize(new java.awt.Dimension(1920, 1080));

        jPanel2.setLayout(null);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/audiokey21/Icons/Tappi.gif"))); // NOI18N
        jLabel9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel9);
        jLabel9.setBounds(940, 1000, 80, 61);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/audiokey21/Icons/ArgoGuinzaglio.gif"))); // NOI18N
        jLabel5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel5);
        jLabel5.setBounds(2840, 1020, 70, 60);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/audiokey21/Icons/BastoneAppuntito.gif"))); // NOI18N
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel2);
        jLabel2.setBounds(2450, 1110, 80, 43);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/audiokey21/Icons/Otrefin.gif"))); // NOI18N
        jLabel8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel8);
        jLabel8.setBounds(1430, 1100, 60, 73);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/audiokey21/Icons/Ferro-di-cavallo.gif"))); // NOI18N
        jLabel7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel7);
        jLabel7.setBounds(600, 960, 70, 48);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/audiokey21/Icons/Loto.gif"))); // NOI18N
        jLabel6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel6);
        jLabel6.setBounds(2030, 1040, 80, 60);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/audiokey21/Icons/FINE-ANIMATO.gif"))); // NOI18N
        jLabel3.setText("jLabel3");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel3);
        jLabel3.setBounds(2920, 980, 120, 70);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/audiokey21/Icons/PIXELFINALE_1.png"))); // NOI18N
        jPanel2.add(jLabel1);
        jLabel1.setBounds(10, 110, 3850, 1440);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 4393, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(2411, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 1517, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1541, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(jPanel1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(-35, -360, 5710, 2761);

        filler1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(filler1);
        filler1.setBounds(11, 1, 0, 0);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void taSuoniKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_taSuoniKeyPressed
        // TODO add your handling code here:
        char chPremuto = evt.getKeyChar();
        if (chPremuto == 'a') {
            playAudio("E:\\NetBeansProjects\\Audiokey21\\Media\\Audio\\Alarm.wav");
        } // endif
        if (chPremuto == 'b') {
            playAudio("media/audio/Alarm02.wav");
        } //endif

    }//GEN-LAST:event_taSuoniKeyPressed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        //POLIFEMO:
        playAudio("media/audio/lancia di legno.wav");
        JOptionPane.showMessageDialog(null, "Questo bastone appuntito mi ricorda polifemo...\n"
                + "Per lui era un regalo lasciarmi per ultimo lasciandomi vedere i miei compagni mangiati vivi, \n"
                + "per fortuna era un gigante di grande forza ma molto poca astuzia, "
                + "è bastato ubriacarlo ed acciecarlo. \n"
                + "Quanto ci siamo divertiti quando ha urlato a squarcia gola agli altri ciclopi che era stato \"nessuno\" ad acciecarlo.", "Bastone Appuntito", JOptionPane.INFORMATION_MESSAGE);

    }//GEN-LAST:event_jLabel2MouseClicked

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        // ARGO:
        playAudio("media/audio/collare di argo.wav");
        JOptionPane.showMessageDialog(null, "Questo guinzaglio mi ricorda Argo, l'unico che è riuscito a riconoscermi dopo anni dalla mia assenza, questo parla già molto \n"
                + "del nostro legame profondo, il più fedele dei viventi, ricordandosi il mio odore dopo tutte le peripezie!", "Guinzaglio", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jLabel5MouseClicked

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        // LOTOFAGI:
        playAudio("media/audio/lotofagi.wav");
        JOptionPane.showMessageDialog(null, "Quella maledetta droga! Il vento ci ha spinto verso l'isola dei lotofagi e i miei uomini si sono abbindolare da quel fiore, ne consumarono \n"
                + "a fiotte convincendosi di voler restare sull'isola. Gli abitanti non erano cattivi, ma non gli avrei affidato nemmeno una gallina!", "Loto", JOptionPane.INFORMATION_MESSAGE);

    }//GEN-LAST:event_jLabel6MouseClicked

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        // CAVALLO DI TROIA:
        playAudio("media/audio/cavallo di troia.wav");
        JOptionPane.showMessageDialog(null, "Questo oggetto mi ricorda qualcosa…\n"
                + "  \n"
                + "Ma certo! Una delle mie trovate più ingegnose!\n"
                + "Erano più di 10 anni che l’assedio alla città di Troia da parte dell’esercito greco non portava alcun successo.\n"
                + "Era una sera tranquilla, io ed i miei compagni ci stavamo riposando in uno dei nostri accampamenti intorno alle mura della città di Troia,\n"
                + "quella sera Atena in persona mi comunicò l’idea per lo stratagemma… Un grande cavallo di legno! \n"
                + "Realizzato con il legno delle nostre scialuppe, l’interno sarebbe stato cavo in modo da contenere almeno 10 soldati greci,\n"
                + "mascherandolo come un offerta per la nostra resa lo avremmo lasciato lì, nei dintorni delle porte Troiane.\n"
                + "  \n"
                + "Il cavallo di Troia permise di cambiare le sorti della guerra, i Troiani videro le spiaggie intorno alla città tutte deserte, \n"
                + "solo un cavallo di legno che svettava in mezzo alle dune sabbiose, lo stratagemma funzionò, pensando che il cavallo \n"
                + "fosse un dono divino lo portarono all’interno delle mura cittadine, i nostri soldati infiltrati aprirono le porte \n"
                + "della città e permisero l’assedio da parte del nostro esercito, la sera stessa la città fu conquistata da noi!\n"
                + "Sicuramente uno dei miei successi più grandi… certo, non avrei mai immaginato quello che mi sarebbe aspettato da li a poco dopo la conquista di Troia…", "Ferro di Cavallo", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jLabel7MouseClicked

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        // OTRE:
        playAudio("media/audio/otre.wav");
        JOptionPane.showMessageDialog(null, "Quel vaso assomiglia molto a quello che mi è stato regalato in quell'isola, l'isola di Eolo. \n"
                + "L'otre che conteneva tutti i venti tranne quello che mi avrebbero portato ad Itaca.\n"
                + "  \n"
                + "Purtroppo quando Itaca era ormai all'orizzonte mi feci prendere dalla stanchezza e mentre sonnicchiavo i miei uomini,\n"
                + "presi dalla curiosità, l'hanno aperto facendo perderci la rotta e facendoci vagare per anni. \n", "Vaso", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jLabel8MouseClicked

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        // TAPPI:
        playAudio("media/audio/sirene.wav");
        JOptionPane.showMessageDialog(null, "Ahh, certo mi ricordo di questi!\n"
                + "La Maga Circe mi mise in guardia, durante il nostro tragitto avremmo potuto incotrare le famigerate sirene, esseri in grado di carpire i sogni e i desideri più reconditi dell’animo umano,\n"
                + "solamente con il loro canto erano capaci di ipnotizzare ed uccidere intere compagnie di uomini di mare, l’unico modo per difendersi da questo terribile destino era quello di tapparsi\n"
                + "le orecchie con della cera.\n"
                + "Così il mio equipaggio si dotò di questi piccoli tappi, solo io decisi che volevo ascoltare il loro canto, mi feci legare con le corde più robuste all’albero maestro della nave ed \n"
                + "istrui la mia ciurma, non avrebbero dovuto slegarmi per nessun motivo, neanche se avessi implorato disperatamente.\n"
                + "  \n"
                + "Il canto delle sirene era dolce e promettevano di mostrarmi i confini del mondo, inutile dire che il loro canto mi ammaliò ma le corde mi tennerò stretto alla nave…\n"
                + "Fortunatamente quel giorno lasciammo le sirene tutti incolumi, almeno credo…", "Tappi di Cera", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jLabel9MouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
      try {

            Desktop D;
            D = Desktop.getDesktop();

            File F;
            F = new File("media/video/INFERNOFullhd_1.mp4");    // "fix imports" per caricare la libreria File

            D.open(F);
            System.exit(1);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Errore: " + e.toString());
        }
    }//GEN-LAST:event_jLabel3MouseClicked
    public void playAudio(String nomeDelFile) {
        try {
            File miofile = new File(nomeDelFile);
            AudioInputStream inputStream = AudioSystem.getAudioInputStream(miofile);
            Clip miaclip = AudioSystem.getClip();
            miaclip.open(inputStream);
            miaclip.start();              // qui è il play                                        
        } catch (IOException | LineUnavailableException | UnsupportedAudioFileException err) {
            JOptionPane.showMessageDialog(this, err.toString());
        }  // endof
        /**
         * @param args the command line arguments
         */

    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FinestraPrincipale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FinestraPrincipale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FinestraPrincipale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FinestraPrincipale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new FinestraPrincipale().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.Box.Filler filler1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

}
